In [1]:
import pandas as pd

In [2]:
SALES = pd.read_csv('lv2-2411.csv')

In [3]:
SALES.shape

(2295, 12)

In [4]:
SALES.head()

,SID,DT,SALES,HOLI,MD1,MD2,MD3,TEMP,FUEL,CPI,UNEMP,TT
0,1,2023-05-08,1594939,0,10383,2407,6551,59.11,3.297,217.998085,7.866,TRAIN
1,2,2023-05-08,1920725,0,10798,4754,4787,59.33,3.297,217.645539,7.441,TRAIN
2,3,2023-05-08,407764,0,8788,571,1005,61.70,3.297,221.411752,7.197,TRAIN
3,4,2023-05-08,2203029,0,12852,5630,9213,47.12,3.286,129.816710,5.143,TEST
4,5,2023-05-08,311907,0,2971,757,1041,60.71,3.297,218.569962,6.300,TRAIN

# Q1

In [5]:
df_1 = SALES.copy()

# 1-1

In [6]:
df_1.columns

Index(['SID', 'DT', 'SALES', 'HOLI', 'MD1', 'MD2', 'MD3', 'TEMP', 'FUEL',
       'CPI', 'UNEMP', 'TT'],
      dtype='object')

In [7]:
targets = ['MD1', 'MD2', 'MD3', 'TEMP', 'FUEL', 'CPI', 'UNEMP']

In [8]:
len(targets)

7

In [9]:
from scipy.stats import pearsonr

In [14]:
ps = []

for target in targets:
    p = pearsonr(x=df_1[target], y=df_1['SALES'])
    ps.append(abs(p[0]))

In [15]:
ps

[np.float64(0.32380918221245397),
 np.float64(0.22771041719737192),
 np.float64(0.3055630511637542),
 np.float64(0.0790400998235723),
 np.float64(0.03596533716437796),
 np.float64(0.07111997609879915),
 np.float64(0.10405810925669297)]

# 1-2

In [16]:
max_ps = max(ps)

In [17]:
max_ps

np.float64(0.32380918221245397)

# Q1 Answer

In [18]:
print(round(max_ps, 3))

0.324

# Q2

In [19]:
df_2 = SALES.copy()

In [20]:
df_2.shape

(2295, 12)

In [21]:
df_2.head()

,SID,DT,SALES,HOLI,MD1,MD2,MD3,TEMP,FUEL,CPI,UNEMP,TT
0,1,2023-05-08,1594939,0,10383,2407,6551,59.11,3.297,217.998085,7.866,TRAIN
1,2,2023-05-08,1920725,0,10798,4754,4787,59.33,3.297,217.645539,7.441,TRAIN
2,3,2023-05-08,407764,0,8788,571,1005,61.70,3.297,221.411752,7.197,TRAIN
3,4,2023-05-08,2203029,0,12852,5630,9213,47.12,3.286,129.816710,5.143,TEST
4,5,2023-05-08,311907,0,2971,757,1041,60.71,3.297,218.569962,6.300,TRAIN

# 2-1

In [22]:
DF22 = df_2[df_2['DT'] == '2024-04-22']

In [23]:
DF22.shape

(45, 12)

# 2-2

In [24]:
DF22.columns

Index(['SID', 'DT', 'SALES', 'HOLI', 'MD1', 'MD2', 'MD3', 'TEMP', 'FUEL',
       'CPI', 'UNEMP', 'TT'],
      dtype='object')

In [25]:
targets = ['SALES', 'MD1', 'MD2', 'MD3', 'TEMP', 'FUEL', 'CPI', 'UNEMP']

In [26]:
len(targets)

8

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
for target in targets:
    DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\840637170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22[target + '_S'] = StandardScaler().fit_transform(X=DF22.loc[:, [target]])

In [29]:
DF22.head()

,SID,DT,SALES,HOLI,MD1,MD2,MD3,TEMP,FUEL,CPI,UNEMP,TT,SALES_S,MD1_S,MD2_S,MD3_S,TEMP_S,FUEL_S,CPI_S,UNEMP_S
2250,1,2024-04-22,1493660,0,2586,1057,1305,69.16,3.506,223.444251,6.573,TRAIN,0.925886,-0.573575,0.748461,-0.322387,0.781573,-1.032914,1.134592,-0.239531
2251,2,2024-04-22,1834458,0,6153,272,2924,69.79,3.506,223.078337,6.170,TEST,1.581120,0.410093,-0.527571,0.686657,0.842296,-1.032914,1.125720,-0.493086
2252,3,2024-04-22,405433,0,371,6,180,74.66,3.506,226.987364,6.034,TRAIN,-1.166390,-1.184403,-0.959958,-1.023546,1.311689,-1.032914,1.220499,-0.578653
2253,4,2024-04-22,2149594,0,1763,0,7577,63.64,3.514,131.193097,3.879,TRAIN,2.187015,-0.800533,-0.969712,3.586649,0.249529,-1.003970,-1.102141,-1.934511
2254,5,2024-04-22,319551,0,1548,133,599,71.70,3.506,224.037814,5.422,TRAIN,-1.331510,-0.859823,-0.753518,-0.762403,1.026391,-1.032914,1.148983,-0.963704

# 2-3

In [30]:
DF22.columns

Index(['SID', 'DT', 'SALES', 'HOLI', 'MD1', 'MD2', 'MD3', 'TEMP', 'FUEL',
       'CPI', 'UNEMP', 'TT', 'SALES_S', 'MD1_S', 'MD2_S', 'MD3_S', 'TEMP_S',
       'FUEL_S', 'CPI_S', 'UNEMP_S'],
      dtype='object')

In [31]:
targets = ['SALES_S', 'MD1_S', 'MD2_S', 'MD3_S', 'TEMP_S', 'FUEL_S', 'CPI_S', 'UNEMP_S']

In [32]:
from sklearn.cluster import KMeans

In [33]:
model = KMeans(n_clusters=4, random_state=1234, init='random').fit(X=DF22.loc[:, targets])

In [34]:
DF22['LABEL'] = model.predict(X=DF22.loc[:, targets])

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_23772\3614196854.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF22['LABEL'] = model.predict(X=DF22.loc[:, targets])

In [35]:
DF22.head()

,SID,DT,SALES,HOLI,MD1,MD2,MD3,TEMP,FUEL,CPI,...,TT,SALES_S,MD1_S,MD2_S,MD3_S,TEMP_S,FUEL_S,CPI_S,UNEMP_S,LABEL
2250,1,2024-04-22,1493660,0,2586,1057,1305,69.16,3.506,223.444251,...,TRAIN,0.925886,-0.573575,0.748461,-0.322387,0.781573,-1.032914,1.134592,-0.239531,2
2251,2,2024-04-22,1834458,0,6153,272,2924,69.79,3.506,223.078337,...,TEST,1.581120,0.410093,-0.527571,0.686657,0.842296,-1.032914,1.125720,-0.493086,2
2252,3,2024-04-22,405433,0,371,6,180,74.66,3.506,226.987364,...,TRAIN,-1.166390,-1.184403,-0.959958,-1.023546,1.311689,-1.032914,1.220499,-0.578653,0
2253,4,2024-04-22,2149594,0,1763,0,7577,63.64,3.514,131.193097,...,TRAIN,2.187015,-0.800533,-0.969712,3.586649,0.249529,-1.003970,-1.102141,-1.934511,2
2254,5,2024-04-22,319551,0,1548,133,599,71.70,3.506,224.037814,...,TRAIN,-1.331510,-0.859823,-0.753518,-0.762403,1.026391,-1.032914,1.148983,-0.963704,0

# 2-4

In [36]:
summary = DF22.groupby('LABEL')['SALES'].mean().reset_index()

In [37]:
summary

   LABEL         SALES
0      0  5.000801e+05
1      1  1.589292e+06
2      2  1.461851e+06
3      3  8.159207e+05

In [38]:
summary['SALES'].idxmax()

1

In [39]:
unemp = DF22.groupby('LABEL')['UNEMP'].mean()

In [40]:
unemp

LABEL
0    6.124875
1    8.201875
2    5.819125
3    7.226190
Name: UNEMP, dtype: float64

# Q2 Answer

In [41]:
print(round(8.201875, 3))

8.202

# Q3

In [42]:
df_3 = SALES.copy()

# 3-1

In [43]:
df_3.head()

,SID,DT,SALES,HOLI,MD1,MD2,MD3,TEMP,FUEL,CPI,UNEMP,TT
0,1,2023-05-08,1594939,0,10383,2407,6551,59.11,3.297,217.998085,7.866,TRAIN
1,2,2023-05-08,1920725,0,10798,4754,4787,59.33,3.297,217.645539,7.441,TRAIN
2,3,2023-05-08,407764,0,8788,571,1005,61.70,3.297,221.411752,7.197,TRAIN
3,4,2023-05-08,2203029,0,12852,5630,9213,47.12,3.286,129.816710,5.143,TEST
4,5,2023-05-08,311907,0,2971,757,1041,60.71,3.297,218.569962,6.300,TRAIN

In [45]:
df_3.iloc[0, :]

SID               1
DT       2023-05-08
SALES       1594939
HOLI              0
MD1           10383
MD2            2407
MD3            6551
TEMP          59.11
FUEL          3.297
CPI      217.998085
UNEMP         7.866
TT            TRAIN
Name: 0, dtype: object

In [53]:
df_3['DT'].astype('str').map(lambda x: x[-5:-3])

0       05
1       05
2       05
3       05
4       05
        ..
2290    04
2291    04
2292    04
2293    04
2294    04
Name: DT, Length: 2295, dtype: object

In [54]:
df_3['SEASON1'] = ((df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '03') |  (df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '04') | (df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '05')) + 0

In [55]:
df_3.head()

,SID,DT,SALES,HOLI,MD1,MD2,MD3,TEMP,FUEL,CPI,UNEMP,TT,SEASON1
0,1,2023-05-08,1594939,0,10383,2407,6551,59.11,3.297,217.998085,7.866,TRAIN,1
1,2,2023-05-08,1920725,0,10798,4754,4787,59.33,3.297,217.645539,7.441,TRAIN,1
2,3,2023-05-08,407764,0,8788,571,1005,61.70,3.297,221.411752,7.197,TRAIN,1
3,4,2023-05-08,2203029,0,12852,5630,9213,47.12,3.286,129.816710,5.143,TEST,1
4,5,2023-05-08,311907,0,2971,757,1041,60.71,3.297,218.569962,6.300,TRAIN,1

In [56]:
df_3['SEASON1'].value_counts()

SEASON1
0    1755
1     540
Name: count, dtype: int64

In [57]:
df_3['SEASON2'] = ((df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '06') |  (df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '07') | (df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '08')) + 0

In [58]:
df_3.head()

,SID,DT,SALES,HOLI,MD1,MD2,MD3,TEMP,FUEL,CPI,UNEMP,TT,SEASON1,SEASON2
0,1,2023-05-08,1594939,0,10383,2407,6551,59.11,3.297,217.998085,7.866,TRAIN,1,0
1,2,2023-05-08,1920725,0,10798,4754,4787,59.33,3.297,217.645539,7.441,TRAIN,1,0
2,3,2023-05-08,407764,0,8788,571,1005,61.70,3.297,221.411752,7.197,TRAIN,1,0
3,4,2023-05-08,2203029,0,12852,5630,9213,47.12,3.286,129.816710,5.143,TEST,1,0
4,5,2023-05-08,311907,0,2971,757,1041,60.71,3.297,218.569962,6.300,TRAIN,1,0

In [59]:
df_3['SEASON3'] = ((df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '09') |  (df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '10') | (df_3['DT'].astype('str').map(lambda x: x[-5:-3]) == '11')) + 0

In [60]:
df_3['SEASON2'].value_counts()

SEASON2
0    1710
1     585
Name: count, dtype: int64

In [61]:
df_3['SEASON3'].value_counts()

SEASON3
0    1710
1     585
Name: count, dtype: int64

# 3-2

In [62]:
TRAIN23 = df_3[df_3['TT'] == 'TRAIN']
TEST23 = df_3[df_3['TT'] == 'TEST']

In [63]:
TRAIN23.shape

(1722, 15)

In [64]:
TEST23.shape

(573, 15)

# 3-3

In [65]:
TRAIN23.columns

Index(['SID', 'DT', 'SALES', 'HOLI', 'MD1', 'MD2', 'MD3', 'TEMP', 'FUEL',
       'CPI', 'UNEMP', 'TT', 'SEASON1', 'SEASON2', 'SEASON3'],
      dtype='object')

In [66]:
targets = ['HOLI', 'MD1', 'MD2', 'MD3', 'TEMP', 'FUEL',  'CPI', 'UNEMP', 'SEASON1', 'SEASON2', 'SEASON3']

In [67]:
len(targets)

11

In [68]:
from sklearn.linear_model import LinearRegression

In [71]:
model = LinearRegression().fit(y=TRAIN23['SALES'], X=TRAIN23.loc[:, targets])

# 3-4

In [72]:
pred = model.predict(X=TEST23.loc[:, targets])

In [73]:
from sklearn.metrics import mean_absolute_percentage_error

In [74]:
mape = mean_absolute_percentage_error(y_true=TEST23['SALES'], y_pred=pred)

In [76]:
mape *= 100

In [77]:
mape

53.59237851260665

# Q3 Answer

In [78]:
print(round(mape, 2))

53.59