In [1]:
import pandas as pd

In [2]:
CULTURE = pd.read_csv('lv2-2407.csv')

In [3]:
CULTURE.shape

(1524, 11)

In [4]:
CULTURE.head()

,C_ID,NEMP,NEMP_PER_HEAD,INT_RATIO,F_RATIO,S1,S2,S3,S4,S5,SCORE
0,1,20965,10.6,42,48,92.3,99.7,99.0,74.9,96.2,96.4
1,2,21887,9.6,25,50,94.8,99.0,99.3,49.5,80.5,95.2
2,3,20185,11.3,39,47,90.9,99.5,97.0,54.2,95.8,94.8
3,4,16164,7.1,24,46,94.2,96.7,99.8,65.0,79.8,94.8
4,5,11415,8.2,33,40,90.7,93.6,99.8,90.9,89.3,94.2

# Q1

In [5]:
df_1 = CULTURE.copy()

In [6]:
df_1.columns

Index(['C_ID', 'NEMP', 'NEMP_PER_HEAD', 'INT_RATIO', 'F_RATIO', 'S1', 'S2',
       'S3', 'S4', 'S5', 'SCORE'],
      dtype='object')

# 1-1

In [7]:
targets = ['NEMP', 'NEMP_PER_HEAD', 'INT_RATIO', 'S1', 'S2', 'S3', 'S4', 'S5', 'SCORE']

In [8]:
len(targets)

9

In [10]:
cvs = []

for target in targets:
    s = df_1[target].std()
    x = df_1[target].mean()
    cv = s/x
    cvs.append(cv)

In [11]:
cvs

[np.float64(0.7370618875840848),
 np.float64(0.5238290399400145),
 np.float64(1.168639328294814),
 np.float64(0.4905155421227808),
 np.float64(0.7291352271443924),
 np.float64(0.5675360208579083),
 np.float64(0.3065498676138587),
 np.float64(0.47797966957986976),
 np.float64(0.4698529953171055)]

In [12]:
len(cvs)

9

# 1-2

In [14]:
from scipy.stats import skew

In [16]:
skews = []

for target in targets:
    skews.append(skew(df_1[target]))

In [17]:
len(skews)

9

# 1-3

In [18]:
from scipy.stats import pearsonr

In [19]:
targets = ['NEMP', 'NEMP_PER_HEAD', 'INT_RATIO', 'S1', 'S2', 'S3', 'S4', 'S5']

In [20]:
len(targets)

8

In [22]:
pearsons = []

for target in targets:
    pearsons.append(pearsonr(x=df_1[target], y=df_1['SCORE'])[0])

In [23]:
pearsons

[np.float64(0.08039633914133486),
 np.float64(-0.03974292797260058),
 np.float64(0.5571226792405014),
 np.float64(0.8102424597188804),
 np.float64(0.8612470921614188),
 np.float64(0.8535500298348543),
 np.float64(0.42487147157165567),
 np.float64(0.6341395520101901)]

In [24]:
len(pearsons)

8

# 1-4

In [25]:
NUM24_A = max(cvs)
NUM24_B = min(skews)
NUM24_C = max(pearsons)
NUM24_D = NUM24_A + NUM24_B + NUM24_C

NUM24_D

np.float64(2.2240447226241615)

# Q1 Answer

In [26]:
print(round(NUM24_D, 3))

2.224

# Q2

In [27]:
df_2 = CULTURE.copy()

In [30]:
df_2.shape

(1524, 11)

# 2-1

In [28]:
DF25 = df_2[df_2['F_RATIO'] != -999].copy()

In [29]:
DF25.shape

(1466, 11)

# 2-2

In [31]:
DF25.columns

Index(['C_ID', 'NEMP', 'NEMP_PER_HEAD', 'INT_RATIO', 'F_RATIO', 'S1', 'S2',
       'S3', 'S4', 'S5', 'SCORE'],
      dtype='object')

In [32]:
targets = ['NEMP', 'NEMP_PER_HEAD', 'INT_RATIO', 'F_RATIO', 'S1', 'S2', 'S3', 'S4', 'S5']

In [33]:
len(targets)

9

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
for target in targets:
    DF25[target + '_S'] = StandardScaler().fit_transform(X=DF25.loc[:, [target]])

In [38]:
DF25.head()

,C_ID,NEMP,NEMP_PER_HEAD,INT_RATIO,F_RATIO,S1,S2,S3,S4,S5,SCORE,NEMP_S,NEMP_PER_HEAD_S,INT_RATIO_S,F_RATIO_S,S1_S,S2_S,S3_S,S4_S,S5_S
0,1,20965,10.6,42,48,92.3,99.7,99.0,74.9,96.2,96.4,0.045785,-0.813352,2.714871,-0.224625,5.160761,4.844856,1.853440,2.173504,2.290136
1,2,21887,9.6,25,50,94.8,99.0,99.3,49.5,80.5,95.2,0.106671,-0.917010,1.271858,-0.066649,5.356333,4.801227,1.864341,0.291133,1.574647
2,3,20185,11.3,39,47,90.9,99.5,97.0,54.2,95.8,94.8,-0.005724,-0.740791,2.460222,-0.303612,5.051240,4.832391,1.780768,0.639446,2.271907
3,4,16164,7.1,24,46,94.2,96.7,99.8,65.0,79.8,94.8,-0.271258,-1.176157,1.186974,-0.382600,5.309396,4.657875,1.882509,1.439824,1.542746
4,5,11415,8.2,33,40,90.7,93.6,99.8,90.9,89.3,94.2,-0.584867,-1.062132,1.950923,-0.856527,5.035594,4.464661,1.882509,3.359250,1.975685

# 2-3

In [39]:
ks = [2, 3, 4]

In [40]:
models = []

In [41]:
tmp = []
for target in targets:
    tmp.append(target + '_S')

In [42]:
targets = tmp
targets

['NEMP_S',
 'NEMP_PER_HEAD_S',
 'INT_RATIO_S',
 'F_RATIO_S',
 'S1_S',
 'S2_S',
 'S3_S',
 'S4_S',
 'S5_S']

In [43]:
from sklearn.cluster import KMeans

In [45]:
for k in ks:
    model = KMeans(n_clusters=k, random_state=1234).fit(X=DF25.loc[:, targets])
    models.append(model)

# 2-4

In [46]:
from sklearn.metrics import silhouette_score

In [47]:
sils = []

for model in models:
    pred = model.predict(X=DF25.loc[:, targets])
    sil = silhouette_score(X=DF25.loc[:, targets], labels=pred)
    sils.append(sil)

In [48]:
sils

[0.3140819970740654, 0.2213049667490972, 0.1807236579880251]

In [51]:
model = models[0]

In [52]:
pred = model.predict(X=DF25.loc[:, targets])

In [53]:
DF25['LABEL'] = pred

In [55]:
DF25.groupby('LABEL')['C_ID'].count()

LABEL
0     379
1    1087
Name: C_ID, dtype: int64

# Q2 Answer

In [58]:
print(round(1087))

1087

# Q3

In [59]:
df_3 = CULTURE.copy()

In [60]:
df_3.shape

(1524, 11)

In [61]:
df_3.head()

,C_ID,NEMP,NEMP_PER_HEAD,INT_RATIO,F_RATIO,S1,S2,S3,S4,S5,SCORE
0,1,20965,10.6,42,48,92.3,99.7,99.0,74.9,96.2,96.4
1,2,21887,9.6,25,50,94.8,99.0,99.3,49.5,80.5,95.2
2,3,20185,11.3,39,47,90.9,99.5,97.0,54.2,95.8,94.8
3,4,16164,7.1,24,46,94.2,96.7,99.8,65.0,79.8,94.8
4,5,11415,8.2,33,40,90.7,93.6,99.8,90.9,89.3,94.2

# 3-1

In [62]:
tmp = df_3[df_3['F_RATIO'] != -999]

In [63]:
tmp.shape

(1466, 11)

In [64]:
tmp_m = tmp['F_RATIO'].mean()
tmp_m

np.float64(50.843792633015006)

In [66]:
df_3['F_RATIO'] = df_3['F_RATIO'].map(lambda x: tmp_m if x == -999 else x)

In [67]:
df_3.head()

,C_ID,NEMP,NEMP_PER_HEAD,INT_RATIO,F_RATIO,S1,S2,S3,S4,S5,SCORE
0,1,20965,10.6,42,48.0,92.3,99.7,99.0,74.9,96.2,96.4
1,2,21887,9.6,25,50.0,94.8,99.0,99.3,49.5,80.5,95.2
2,3,20185,11.3,39,47.0,90.9,99.5,97.0,54.2,95.8,94.8
3,4,16164,7.1,24,46.0,94.2,96.7,99.8,65.0,79.8,94.8
4,5,11415,8.2,33,40.0,90.7,93.6,99.8,90.9,89.3,94.2

# 3-2

In [68]:
TRAIN26 = df_3[df_3['C_ID'] % 5 != 0].copy()
TEST26 = df_3[df_3['C_ID'] % 5 == 0].copy()

In [69]:
TRAIN26.shape

(1220, 11)

In [70]:
TEST26.shape

(304, 11)

# 3-3

In [71]:
from sklearn.linear_model import LinearRegression

In [72]:
TRAIN26.columns

Index(['C_ID', 'NEMP', 'NEMP_PER_HEAD', 'INT_RATIO', 'F_RATIO', 'S1', 'S2',
       'S3', 'S4', 'S5', 'SCORE'],
      dtype='object')

In [73]:
targets = ['NEMP', 'NEMP_PER_HEAD', 'INT_RATIO', 'F_RATIO', 'S1', 'S2', 'S3', 'S4', 'S5']

In [74]:
model = LinearRegression().fit(y=TRAIN26['SCORE'], X=TRAIN26.loc[:, targets])

# 3-4

In [77]:
coef = []

for c in model.coef_:
    coef.append(abs(c))

In [78]:
coef

[np.float64(3.4311381598522005e-07),
 np.float64(0.00042087949596003593),
 np.float64(0.0038942270744812754),
 np.float64(0.004235255248771198),
 np.float64(0.2937749521765868),
 np.float64(0.30424343488828154),
 np.float64(0.3017838724509036),
 np.float64(0.023142466229746573),
 np.float64(0.07971709501247581)]

In [79]:
max(coef)

np.float64(0.30424343488828154)

In [80]:
NUM26_A = max(coef)

# 3-5

In [81]:
from sklearn.metrics import mean_absolute_percentage_error

In [83]:
NUM26_B = 100 * mean_absolute_percentage_error(y_true=TEST26['SCORE'], y_pred=model.predict(X=TEST26.loc[:, targets]))

In [84]:
NUM26_B

5.233174583714302

# Q3 Answer

In [86]:
print(round(NUM26_A + NUM26_B, 4))

5.5374