In [1]:
import pandas as pd

In [2]:
SURVEY = pd.read_csv('lv2-2403.csv')

In [3]:
SURVEY.shape

(11351, 11)

In [4]:
SURVEY.head()

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE
0,1,1,1,0,0-2 years,4.5,NaN,1,Git,Female,25-34 years old
1,2,1,0,0,18-20 years,2.8,75000.0,3,Git,NaN,over 35
2,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old
3,4,1,1,0,9-11 years,4.0,NaN,2,Git,NaN,over 35
4,5,1,0,1,6-8 years,1.5,44000.0,2,Git;Zip file back-ups,Female,under 25

# Q1

In [20]:
df_1 = SURVEY.copy()

# 1-1

In [21]:
DF1 = df_1.dropna(subset='SALARY')

In [22]:
DF1.shape

(8526, 11)

# 1-2

In [23]:
AVG1 = DF1['SALARY'].mean()

In [24]:
AVG1

np.float64(98525.35186488388)

# 1-3

In [25]:
import numpy as np

In [26]:
years = DF1['YEARS'].value_counts().reset_index()['YEARS']

In [27]:
years

0            3-5 years
1            6-8 years
2           9-11 years
3          12-14 years
4          15-17 years
5            0-2 years
6          18-20 years
7     30 or more years
8          21-23 years
9          24-26 years
10         27-29 years
Name: YEARS, dtype: object

In [28]:
for year in years:
    DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)

In [29]:
DF1

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE,IN
1,2,1,0,0,18-20 years,2.8,75000.0,3,Git,NaN,over 35,1
2,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old,1
4,5,1,0,1,6-8 years,1.5,44000.0,2,Git;Zip file back-ups,Female,under 25,1
5,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old,1
6,7,1,1,0,15-17 years,6.4,90000.0,2,Git,NaN,25-34 years old,1
...,...,...,...,...,...,...,...,...,...,...,...,...
11343,11344,1,0,0,21-23 years,6.2,67313.0,2,Git,Male,over 35,1
11344,11345,1,0,0,9-11 years,6.6,31788.0,1,I don't use version control,Male,25-34 years old,1
11346,11347,1,1,0,18-20 years,6.4,70000.0,1,Git,Female,over 35,1
11347,11348,0,0,0,30 or more years,1.6,80000.0,3,Git,Male,over 35,1
11350,11351,1,1,0,30 or more years,1.6,85000.0,2,Git,Male,over 35,1

In [32]:
DF1['IN'].value_counts()

IN
1    8214
0     312
Name: count, dtype: int64

In [34]:
DF1 = DF1[DF1['IN'] == 1].copy()

In [36]:
DF1 = DF1.drop(columns=['IN'])

# 1-4

In [37]:
AVG2 = DF1['SALARY'].mean()

In [38]:
abs(AVG1 - AVG2)

np.float64(34470.182519863185)

# Q1 Answer

In [40]:
print(round(abs(AVG1 - AVG2)))

34470

# Q2

In [51]:
df_2 = SURVEY.copy()

# 2-1

In [52]:
DF2 = df_2[df_2['AGE'] == '25-34 years old']

In [53]:
DF2.shape

(6209, 11)

# 2-2

In [54]:
df2_tmp = DF2.dropna(subset='SALARY')

In [55]:
df2_median = df2_tmp['SALARY'].median()

In [56]:
DF2['SALARY'] = DF2['SALARY'].fillna(value=df2_median)

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_14460\1521987472.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['SALARY'] = DF2['SALARY'].fillna(value=df2_median)

In [57]:
df2_tmp = DF2.dropna(subset='SALARY')

In [58]:
df2_tmp.shape

(6209, 11)

In [59]:
DF2 = DF2.sort_values(by='D_ID').reset_index(drop=True)

In [60]:
DF2

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE
0,1,1,1,0,0-2 years,4.5,56277.0,1,Git,Female,25-34 years old
1,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old
2,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old
3,7,1,1,0,15-17 years,6.4,90000.0,2,Git,NaN,25-34 years old
4,8,1,1,1,12-14 years,6.1,120000.0,2,Git;Subversion;Zip file back-ups,Male,25-34 years old
...,...,...,...,...,...,...,...,...,...,...,...
6204,11339,1,0,0,6-8 years,2.0,29170.0,2,Team Foundation Version Control,Male,25-34 years old
6205,11340,0,0,0,9-11 years,1.2,12000.0,1,Zip file back-ups,Male,25-34 years old
6206,11341,1,1,0,15-17 years,7.4,87000.0,2,Git;Mercurial,Male,25-34 years old
6207,11345,1,0,0,9-11 years,6.6,31788.0,1,I don't use version control,Male,25-34 years old
6208,11349,1,1,0,18-20 years,6.3,56277.0,1,Git,Female,25-34 years old

# 2-4

In [61]:
targets = ['SATIS', 'SALARY', 'MONITORS', 'TOO_CNT']