In [1]:
import pandas as pd
import numpy as np

In [2]:
CUSTOMER = pd.read_csv('lv2-2404.csv')

In [3]:
CUSTOMER.shape

(900, 11)

In [4]:
CUSTOMER.head()

,CUS_ID,REGION,TENURE,AGE,INCOME,MARITAL,ED,EMPLOY,RETIRE,GENDER,CUSTCAT
0,1,1,67,40,59,1,3,11,0,0,Class C
1,2,1,50,43,27,0,3,4,0,0,Class C
2,3,1,3,24,20,1,2,3,0,1,Class C
3,4,1,40,42,108,1,3,17,0,0,Class B
4,5,2,48,35,50,0,1,16,0,0,Class C

# Q1

# 1-1

In [29]:
df_1 = CUSTOMER.copy()

In [30]:
df_1['REGION'].value_counts().reset_index().sort_values(by='REGION').reset_index(drop=True)

   REGION  count
0       1    291
1       2    296
2       3    313

In [31]:
rt = pd.DataFrame()

In [32]:
rt['region'] = df_1.groupby('REGION')['TENURE'].mean().reset_index()['REGION']
rt['mean'] = df_1.groupby('REGION')['TENURE'].mean().reset_index()['TENURE']

In [33]:
rt['std'] = df_1.groupby('REGION')['TENURE'].std().reset_index()['TENURE']

In [37]:
rt['cnt'] = df_1['REGION'].value_counts().reset_index().sort_values(by='REGION').reset_index(drop=True)['count']

In [38]:
rt

   region       mean        std  cnt
0       1  35.099656  21.282347  291
1       2  35.361486  20.526983  296
2       3  36.057508  22.329767  313

In [39]:
df_1['REGION'].value_counts()

REGION
3    313
2    296
1    291
Name: count, dtype: int64

# 1-2

In [40]:
t_range = {'290': 1.968178, '295': 1.968038, '312': 1.967596}

In [48]:
min_t = []

min_t.append(rt.loc[0, 'mean'] - t_range[str(rt.loc[0, 'cnt'] - 1)] * rt.loc[0, 'std'] / (rt.loc[0, 'cnt'] ** 0.5))
min_t.append(rt.loc[1, 'mean'] - t_range[str(rt.loc[1, 'cnt'] - 1)] * rt.loc[1, 'std'] / (rt.loc[1, 'cnt'] ** 0.5))
min_t.append(rt.loc[2, 'mean'] - t_range[str(rt.loc[2, 'cnt'] - 1)] * rt.loc[2, 'std'] / (rt.loc[2, 'cnt'] ** 0.5))

In [49]:
min_t

[np.float64(32.644170674241415),
 np.float64(33.01340728746268),
 np.float64(33.57410072843366)]

In [50]:
max_t = []

max_t.append(rt.loc[0, 'mean'] + t_range[str(rt.loc[0, 'cnt'] - 1)] * rt.loc[0, 'std'] / (rt.loc[0, 'cnt'] ** 0.5))
max_t.append(rt.loc[1, 'mean'] + t_range[str(rt.loc[1, 'cnt'] - 1)] * rt.loc[1, 'std'] / (rt.loc[1, 'cnt'] ** 0.5))
max_t.append(rt.loc[2, 'mean'] + t_range[str(rt.loc[2, 'cnt'] - 1)] * rt.loc[2, 'std'] / (rt.loc[2, 'cnt'] ** 0.5))

In [51]:
max_t

[np.float64(37.55514204053522),
 np.float64(37.70956568551029),
 np.float64(38.54091524600723)]

# 1-3

In [52]:
A = max(max_t)
B = min(min_t)
A + B

np.float64(71.18508592024864)

# Q1 Answer

In [53]:
print(round(A + B, 2))

71.19

# Q2

In [75]:
df_2 = CUSTOMER.copy()

# 2-1

In [76]:
df_2.columns

Index(['CUS_ID', 'REGION', 'TENURE', 'AGE', 'INCOME', 'MARITAL', 'ED',
       'EMPLOY', 'RETIRE', 'GENDER', 'CUSTCAT'],
      dtype='object')

In [77]:
targets = ['TENURE', 'AGE', 'INCOME', 'EMPLOY']

In [78]:
from sklearn.preprocessing import StandardScaler

In [79]:
for target in targets:
    df_2[target + '_S'] = StandardScaler().fit_transform(X=df_2.loc[:, [target]])

In [80]:
df_2

,CUS_ID,REGION,TENURE,AGE,INCOME,MARITAL,ED,EMPLOY,RETIRE,GENDER,CUSTCAT,TENURE_S,AGE_S,INCOME_S,EMPLOY_S
0,1,1,67,40,59,1,3,11,0,0,Class C,1.472498,-0.128495,-0.160074,0.009789
1,2,1,50,43,27,0,3,4,0,0,Class C,0.677340,0.109296,-0.454744,-0.683155
2,3,1,3,24,20,1,2,3,0,1,Class C,-1.521039,-1.396714,-0.519203,-0.782147
3,4,1,40,42,108,1,3,17,0,0,Class B,0.209600,0.030032,0.291141,0.603741
4,5,2,48,35,50,0,1,16,0,0,Class C,0.583792,-0.524814,-0.242950,0.504749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,896,1,45,52,46,0,5,8,0,1,Class B,0.443470,0.822669,-0.279784,-0.287187
896,897,1,8,29,21,1,5,0,0,0,Class A,-1.287169,-1.000396,-0.509995,-1.079123
897,898,1,29,32,49,1,4,3,0,1,Class B,-0.304915,-0.762605,-0.252158,-0.782147
898,899,3,20,48,24,1,2,3,0,0,Class D,-0.725881,0.505614,-0.482370,-0.782147
899,900,2,23,30,30,1,1,2,0,0,Class C,-0.585559,-0.921132,-0.427119,-0.881139

# 2-2

In [81]:
from sklearn.cluster import KMeans

In [82]:
targets = ['TENURE_S', 'AGE_S', 'INCOME_S', 'EMPLOY_S']

In [84]:
model = KMeans(n_clusters=4, random_state=1234).fit(X=df_2.loc[:, targets])

# 2-3

In [85]:
model.cluster_centers_

array([[ 0.86163351, -0.151142  , -0.16228031, -0.16538558],
       [-0.86822459, -0.84369578, -0.3459412 , -0.71425029],
       [ 1.11639163,  1.22215791,  1.11787596,  1.69463313],
       [-0.2858026 ,  0.76471271, -0.06680092,  0.15880943]])

In [86]:
len(model.cluster_centers_)

4

# 2-4

In [89]:
centres = model.cluster_centers_

In [90]:
df_2['LABEL'] = model.predict(X = df_2.loc[:, targets])

In [93]:
dfs = []

for i in range(4):
    df = df_2[df_2['LABEL'] == i].copy()
    df['DIS'] = ((df['TENURE_S'] - centres[i][0]) ** 2 + (df['AGE_S'] - centres[i][1]) ** 2 + (df['INCOME_S'] - centres[i][2]) ** 2 + (df['EMPLOY_S'] - centres[i][3]) ** 2) ** 0.5
    dfs.append(df)

In [94]:
dfs

[     CUS_ID  REGION  TENURE  AGE  INCOME  MARITAL  ED  EMPLOY  RETIRE  GENDER  \
 0         1       1      67   40      59        1   3      11       0       0
 1         2       1      50   43      27        0   3       4       0       0
 4         5       2      48   35      50        0   1      16       0       0
 8         9       3      55   47      37        0   1      11       0       0
 10       11       2      61   52      19        1   1       0       0       0
 ..      ...     ...     ...  ...     ...      ...  ..     ...     ...     ...
 867     868       1      56   46      33        1   4       7       0       0
 877     878       3      44   37      41        1   4       8       0       1
 878     879       3      67   42      81        1   3      20       0       1
 879     880       1      60   37      64        1   5       1       0       1
 880     881       1      65   45      67        1   5      13       0       1

      CUSTCAT  TENURE_S     AGE_S  INCOME_S  EMPLOY_S  LABEL       DIS
 0    Class C  1.472498 -0.128495 -0.160074  0.009789      0  0.635892
 1    Class C  0.677340  0.109296 -0.454744 -0.683155      0  0.674842
 4    Class C  0.583792 -0.524814 -0.242950  0.504749      0  0.820009
 8    Class C  0.911210  0.426351 -0.362660  0.009789      0  0.637804
 10   Class C  1.191854  0.822669 -0.528412 -1.079123      0  1.423489
 ..       ...       ...       ...       ...       ...    ...       ...
 867  Class B  0.957984  0.347087 -0.399494 -0.386179      0  0.602109
 877  Class B  0.396696 -0.366286 -0.325826 -0.287187      0  0.551396
 878  Class D  1.472498  0.030032  0.042512  0.900717      0  1.258767
 879  Class B  1.145080 -0.366286 -0.114031 -0.980131      0  0.890374
 880  Class C  1.378950  0.267823 -0.086406  0.207773      0  0.766911

 [217 rows x 17 columns],
      CUS_ID  REGION  TENURE  AGE  INCOME  MARITAL  ED  EMPLOY  RETIRE  GENDER  \
 2         3       1       3   24      20        1   2       3       0       1
 5         6       1      38   33      38        0   4       0       0       0
 11       12       1      13   32      31        0   4       5       0       0
 14       15       2      34   23      24        1   1       7       0       1
 15       16       2      13   38     104        1   4       6       0       0
 ..      ...     ...     ...  ...     ...      ...  ..     ...     ...     ...
 891     892       2      11   20      20        0   2       0       0       1
 892     893       3       8   35      31        0   5       7       0       0
 896     897       1       8   29      21        1   5       0       0       0
 897     898       1      29   32      49        1   4       3       0       1
 899     900       2      23   30      30        1   1       2       0       0

      CUSTCAT  TENURE_S     AGE_S  INCOME_S  EMPLOY_S  LABEL       DIS
 2    Class C -1.521039 -1.396714 -0.519203 -0.782147      1  0.875571
 5    Class B  0.116052 -0.683341 -0.353451 -1.079123      1  1.061933
 11   Class C -1.053299 -0.762605 -0.417910 -0.584163      1  0.250860
 14   Class C -0.071045 -1.475978 -0.482370 -0.386179      1  1.077739
 15   Class D -1.053299 -0.287023  0.254307 -0.485171      1  0.870007
 ..       ...       ...       ...       ...       ...    ...       ...
 891  Class D -1.146847 -1.713769 -0.519203 -1.079123      1  0.998904
 892  Class D -1.287169 -0.524814 -0.417910 -0.386179      1  0.624508
 896  Class A -1.287169 -1.000396 -0.509995 -1.079123      1  0.600096
 897  Class B -0.304915 -0.762605 -0.252158 -0.782147      1  0.580775
 899  Class C -0.585559 -0.921132 -0.427119 -0.881139      1  0.346898

 [347 rows x 17 columns],
      CUS_ID  REGION  TENURE  AGE  INCOME  MARITAL  ED  EMPLOY  RETIRE  GENDER  \
 9        10       3      65   58      83        0   2      16       0       1
 18       19       3      11   48     323        1   4      25       0       0
 24       25       2      46   55     269        0   2      35       0       0
 31       32       2      72   60      31        1   1      38       1       0
 61       62       2      46   47     144        0   3      22       0       1
 ..      ...     ...     ...  ...     ...      ...  ..     ...     ...     ...
 874     875       3      66   50     333        1   5      24       0       0
 882     883       1      38   55     135        1   2      24       0       0
 886     887       3      16   50     263        0   2      29       0       1
 890     891       2      39   44     418        1   4      18       0       0
 893     894       2      67   60      93        1   1      21       0       0

      CUSTCAT  TENURE_S     AGE_S  INCOME_S  EMPLOY_S  LABEL       DIS
 9    Class B  1.378950  1.298251  0.060929  0.504749      2  1.614833
 18   Class C -1.146847  0.505614  2.270959  1.395677      2  2.656061
 24   Class C  0.490244  1.060460  1.773702  2.385597      2  1.151411
 31   Class B  1.706368  1.456778 -0.417910  2.682573      2  1.933335
 61   Class C  0.490244  0.426351  0.622645  1.098701      2  1.275053
 ..       ...       ...       ...       ...       ...    ...       ...
 874  Class B  1.425724  0.664142  2.363043  1.296685      2  1.454604
 882  Class D  0.116052  1.060460  0.539769  1.296685      2  1.232638
 886  Class C -0.912977  0.664142  1.718452  1.791645      2  2.190849
 890  Class D  0.162826  0.188559  3.145762  0.702733      2  2.659662
 893  Class B  1.472498  1.456778  0.153014  0.999709      2  1.263225

 [150 rows x 17 columns],
      CUS_ID  REGION  TENURE  AGE  INCOME  MARITAL  ED  EMPLOY  RETIRE  GENDER  \
 3         4       1      40   42     108        1   3      17       0       0
 6         7       3      52   64      43        0   3       7       0       0
 7         8       2      55   57      34        1   2      12       0       0
 12       13       2      30   52      17        0   3       3       0       1
 13       14       1      42   47     212        1   4      17       0       0
 ..      ...     ...     ...  ...     ...      ...  ..     ...     ...     ...
 887     888       1      20   41      67        1   4      14       0       1
 888     889       2      53   63      43        1   2      18       0       0
 894     895       2      53   57      37        0   1       7       0       0
 895     896       1      45   52      46        0   5       8       0       1
 898     899       3      20   48      24        1   2       3       0       0

      CUSTCAT  TENURE_S     AGE_S  INCOME_S  EMPLOY_S  LABEL       DIS
 3    Class B  0.209600  0.030032  0.291141  0.603741      3  1.054166
 6    Class D  0.770888  1.773833 -0.307409 -0.386179      3  1.577917
 7    Class A  0.911210  1.218987 -0.390285  0.108781      3  1.321495
 12   Class B -0.258141  0.822669 -0.546829 -0.782147      3  1.058277
 13   Class C  0.303148  0.426351  1.248820  0.603741      3  1.546019
 ..       ...       ...       ...       ...       ...    ...       ...
 887  Class A -0.725881 -0.049232 -0.086406  0.306765      3  0.937256
 888  Class B  0.817662  1.694569 -0.307409  0.702733      3  1.560773
 894  Class B  0.817662  1.218987 -0.362660 -0.386179      3  1.344821
 895  Class B  0.443470  0.822669 -0.279784 -0.287187      3  0.882877
 898  Class D -0.725881  0.505614 -0.482370 -0.782147      3  1.148432

 [186 rows x 17 columns]]

# 2-5

In [95]:
stds = []

for df in dfs:
    stds.append(df['DIS'].std())

In [96]:
stds

[np.float64(0.3657545184481609),
 np.float64(0.27208825721613794),
 np.float64(1.474457355653116),
 np.float64(0.4628335951704389)]

In [97]:
min(stds)

np.float64(0.27208825721613794)

# Q2 Answer

In [99]:
print(round(min(stds), 3))

0.272

# Q3

In [100]:
df_3 = CUSTOMER.copy()

# 3-1

In [118]:
DF23 = df_3[(df_3['CUSTCAT'] == 'Class A') | (df_3['CUSTCAT'] == 'Class D')].copy()

# 3-2

In [119]:
ages = [50, 40, 30]

In [120]:
DF23['AGE_GROUP'] = DF23['CUS_ID'].map(lambda x: 'AGE_50')

In [121]:
for age in ages:
    DF23['AGE_GROUP'] = np.where((DF23['AGE'] < age), 'AGE_' + str(age - 10),  DF23['AGE_GROUP'])

In [122]:
DF23['AGE_GROUP'].value_counts()

AGE_GROUP
AGE_30    136
AGE_40    106
AGE_20    104
AGE_50    103
Name: count, dtype: int64

# 3-3

In [123]:
DF23.head()

,CUS_ID,REGION,TENURE,AGE,INCOME,MARITAL,ED,EMPLOY,RETIRE,GENDER,CUSTCAT,AGE_GROUP
6,7,3,52,64,43,0,3,7,0,0,Class D,AGE_50
7,8,2,55,57,34,1,2,12,0,0,Class A,AGE_50
15,16,2,13,38,104,1,4,6,0,0,Class D,AGE_30
17,18,3,7,24,29,0,2,3,0,0,Class A,AGE_20
20,21,3,18,28,22,1,1,2,0,1,Class A,AGE_20

In [124]:
DF23.columns

Index(['CUS_ID', 'REGION', 'TENURE', 'AGE', 'INCOME', 'MARITAL', 'ED',
       'EMPLOY', 'RETIRE', 'GENDER', 'CUSTCAT', 'AGE_GROUP'],
      dtype='object')

In [125]:
targets = ['REGION', 'ED', 'AGE_GROUP']

In [126]:
DF23 = pd.get_dummies(DF23, drop_first=True, columns=targets, dtype='int')

In [127]:
DF23.head()

,CUS_ID,TENURE,AGE,INCOME,MARITAL,EMPLOY,RETIRE,GENDER,CUSTCAT,REGION_2,REGION_3,ED_2,ED_3,ED_4,ED_5,AGE_GROUP_AGE_30,AGE_GROUP_AGE_40,AGE_GROUP_AGE_50
6,7,52,64,43,0,7,0,0,Class D,0,1,0,1,0,0,0,0,1
7,8,55,57,34,1,12,0,0,Class A,1,0,1,0,0,0,0,0,1
15,16,13,38,104,1,6,0,0,Class D,1,0,0,0,1,0,1,0,0
17,18,7,24,29,0,3,0,0,Class A,0,1,1,0,0,0,0,0,0
20,21,18,28,22,1,2,0,1,Class A,0,1,0,0,0,0,0,0,0

# 3-4

In [131]:
TRAIN23 = DF23[DF23['CUS_ID'] % 5 != 0]
TEST23 = DF23[DF23['CUS_ID'] % 5 == 0]

In [132]:
TRAIN23.shape

(356, 18)

In [133]:
TEST23.shape

(93, 18)

# 3-5

In [134]:
from sklearn.tree import DecisionTreeClassifier

In [135]:
TRAIN23.columns

Index(['CUS_ID', 'TENURE', 'AGE', 'INCOME', 'MARITAL', 'EMPLOY', 'RETIRE',
       'GENDER', 'CUSTCAT', 'REGION_2', 'REGION_3', 'ED_2', 'ED_3', 'ED_4',
       'ED_5', 'AGE_GROUP_AGE_30', 'AGE_GROUP_AGE_40', 'AGE_GROUP_AGE_50'],
      dtype='object')

In [136]:
targets = ['TENURE', 'INCOME', 'MARITAL', 'EMPLOY', 'RETIRE', 'GENDER', 'REGION_2', 'REGION_3', 'ED_2', 'ED_3', 'ED_4', 'ED_5', 'AGE_GROUP_AGE_30', 'AGE_GROUP_AGE_40', 'AGE_GROUP_AGE_50']

In [137]:
len(targets)

15

In [138]:
model = DecisionTreeClassifier(max_depth=3, random_state=1234).fit(y=TRAIN23['CUSTCAT'], X=TRAIN23.loc[:, targets])

# 3-6

In [139]:
from sklearn.metrics import precision_score

In [140]:
pred = model.predict(X=TEST23.loc[:, targets])

In [142]:
precision_score(y_true=TEST23['CUSTCAT'], y_pred=pred, pos_label='Class A')

0.578125

# Q3 Answer

In [143]:
print(round(precision_score(y_true=TEST23['CUSTCAT'], y_pred=pred, pos_label='Class A'), 3))

0.578